### ISSUE TITLE
Not easy to run the converter scripts on non-windows platforms

### ISSUE THREAD

**Issue by MikeDX** [DenisGrachev/Ringo-8#1]
`SJASM` is a cross platform tool, so Ringo-8 works well on any platform.

The converters however do not.

I have rewritten the sprite and tile tools in python (not that I particularly like python, it is just an easy cross platform solution)

The only dependency is the "Pillow" image library

@DenisGrachev I am happy to submit a PR for this, but unsure where you'd like this to live.

At the moment I have created new subfolders in the "GFX_Converters" named "cs" and "python" and moved the original cs code into the cs folder, and my new python scripts to the python directory. Is that acceptable?

Still working out some things with the scripts as it may make sense to combine the two into one that takes different parameters, or makes a best guess based upon the image sizes.

I have tested the output from the new python code against the existing binaries in the repo and they match perfectly.

**Comment by DenisGrachev** [comment]
thanks for support! Just merge it, hope everything ok since i'm a bit new on git %)
